### ISSUE TITLE
Custom Banlist not working

### ISSUE THREAD

**Issue by VVind0wM4ker** [jpgohlke/twitch-chat-filter#169]
I have a problem with this plugin. 
When I activate it I get all the options, it also looks like it would work fine. Uncolor messages, remove emoticons, etc... works perfect, but banned phrases are still visible.

I opened chat twice, activated script for normal chat. Used popout chat as original chat. No matter wich phrases i banned, they shown up in both chats.

**Comment by hugomg** [comment]
The banned phrases seem to be working fine for me (greasemonkey on firefox). Are you using the latest version of TCF? What is your browser? If you open your developer console (F12) do you  see any error messages?

**Comment by VVind0wM4ker** [comment]
Yes I'm using the newest TCF version (on Google Chrome) using Javascript bookmark. Here is my console output, starting at the point where I started TCF, waited until a banned phrase was sent:

"
TPP Chat Filter version 2.9 loaded. Please report bugs and suggestions to https://github.com/jpgohlke/twitch-chat-filter

TMI.js [conn] WARNING: Unable to connect. Attempting to connect again in 4 seconds...						www-origin.justin.tv//tmilibs/tmi-v3.rf6513ff1dae59857040d6dfc856eea4f339ac26f.js:1

TMI.js [irc] WARNING: Could not parse IRC message: CAP.														www-origin.justin.tv//tmilibs/tmi-v3.rf6513ff1dae59857040d6dfc856eea4f339ac26f.js:1

TMI.js [irc] WARNING: Invalid emotes tag: 																	www-origin.justin.tv//tmilibs/tmi-v3.rf6513ff1dae59857040d6dfc856eea4f339ac26f.js:1

[conn] ERROR: Error handling Flash socket data: TypeError: Cannot read property 'nickname' of undefined		
www-origin.justin.tv//tmilibs/tmi-v3.rf6513ff1dae59857040d6dfc856eea4f339ac26f.js:1 TMI.js 
   
 at RoomConnection._onIrcMessage (http://www-origin.justin.tv//tmilibs/tmi-                                                                    v3.rf6513ff1dae59857040d6dfc856eea4f339ac26f.js:3:8630)
    at EventsDispatcher._trigger (http://www-origin.justin.tv//tmilibs/tmi-v3.rf6513ff1dae59857040d6dfc856eea4f339ac26f.js:1:3524)
    at Connection._onSocketDataReceived (http://www-origin.justin.tv//tmilibs/tmi-v3.rf6513ff1dae59857040d6dfc856eea4f339ac26f.js:3:20068)
    at EventsDispatcher._trigger (http://www-origin.justin.tv//tmilibs/tmi-v3.rf6513ff1dae59857040d6dfc856eea4f339ac26f.js:1:3524)
    at FlashSocket._onDataReceived (http://www-origin.justin.tv//tmilibs/tmi-v3.rf6513ff1dae59857040d6dfc856eea4f339ac26f.js:1:16921)
    at FlashSocket._onEvent (http://www-origin.justin.tv//tmilibs/tmi-v3.rf6513ff1dae59857040d6dfc856eea4f339ac26f.js:1:15572)
    at http://www-origin.justin.tv//tmilibs/tmi-v3.rf6513ff1dae59857040d6dfc856eea4f339ac26f.js:1:13631

TMI.js [irc] WARNING: Could not parse IRC message: 353.														www-origin.justin.tv//tmilibs/tmi-v3.rf6513ff1dae59857040d6dfc856eea4f339ac26f.js:1

TMI.js [irc] WARNING: Could not parse IRC message: 366.														www-origin.justin.tv//tmilibs/tmi-v3.rf6513ff1dae59857040d6dfc856eea4f339ac26f.js:1 

TMI.js [irc] WARNING: Invalid emotes tag: 																	www-origin.justin.tv//tmilibs/7tmi-v3.rf6513ff1dae59857040d6dfc856eea4f339ac26f.js:1
"

But I also get these TMI.js [irc] messages without plugin loaded so I don't think that this is the problem...
